theme: jekyll-theme-midnight
title: Dylan Tran
description: This is my blog. I am learning pentesting and red teaming stuff. 
github:
  is_project_page: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: Dylan
